alter table if exists category drop constraint if exists fk_category_user;
alter table if exists note drop constraint if exists fk_note_category;

drop table if exists category cascade;
drop table if exists note cascade;
drop table if exists users cascade;

create table category
(
    id      int8 generated by default as identity,
    name    varchar(255),
    user_id int8,
    primary key (id)
);

create table note
(
    id          int8 generated by default as identity,
    content     varchar(255),
    category_id int8,
    primary key (id)
);

create table users
(
    id        int8 not null,
    action    varchar(255),
    bot_state varchar(255),
    primary key (id)
);

alter table if exists category
    add constraint fk_category_user foreign key (user_id) references users;
alter table if exists note
    add constraint fk_note_category foreign key (category_id) references category;
